//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterleasing.Reports.StatusWnioskowSW.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("masterleasing.Reports.StatusWnioskowSW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;&lt;style type=&quot;text/css&quot;&gt;
        ///.style1 {
        ///	border-style: solid;
        ///	border-width: 0px;
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;&lt;body style=&quot;font-family: Arial&quot;&gt;&lt;table style=&quot;width: 680px&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;table style=&quot;width: 100%&quot;&gt;&lt;tr&gt;&lt;td align=&quot;center&quot; valign=&quot;middle&quot;&gt;&lt;h3&gt;Zestawienie bieżących kontraktów&lt;/h3&gt;&lt;/td&gt;&lt;td align=&quot;right&quot;&gt;&lt;img alt=&quot;logo&quot; src=&quot;http://stafix24cdn.blob.core.windows.net/sharedfiles/masterleasingLogo.PNG&quot; width=&quot;110&quot;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;table cellpadding=&quot;2&quot; cellspacing=&quot;1&quot; class=&quot;style1&quot; style=&quot;w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLTemplate_StatusWnioskow {
            get {
                return ResourceManager.GetString("HTMLTemplate_StatusWnioskow", resourceCulture);
            }
        }
    }
}
